### ISSUE TITLE
Source generators with syntax receivers should be converted to IIncrementalGenerator

### ISSUE THREAD

**Issue by sharwell** [modernuo/SerializationGenerator#3]
I noticed during a performance investigation that this repository uses a source generator with a syntax receiver:

https://github.com/modernuo/SerializationGenerator/blob/3c5381963e810163be0839596e4234db7bb01764/SerializationGenerator/EntitySerializationGenerator.cs#L29

These source generators can be converted to `IIncrementalGenerator` (Roslyn 4.0+) to dramatically improve overall performance.

**Comment by kamronbatman** [comment]
@sharwell sorry for not seeing your issues. Not sure why my notifications are not working. Anyways, I forgot to address this, thank you!
