### ISSUE TITLE
SerializableMigrationSchema contains an invalid static cache

### ISSUE THREAD

**Issue by sharwell** [modernuo/SerializationGenerator#4]
The following cache maps a _name_ to deserialized content. If the content of the file changes, future compilations may fail to update the serialization, resulting in undefined output.

https://github.com/modernuo/SerializationGenerator/blob/98d0d9dd64a7f5c069f69de23e3201947f82d7c8/SerializationGenerator/SerializableMigration/SerializableMigrationSchema.cs#L38

The recommended resolution here is moving to `IIncrementalGenerator`, which allows value-based deserialization and caching of content provided to source generators through additional files.

**Comment by kamronbatman** [comment]
Thank you! You are definitely right. I may need help accomplishing this since I am new to source generators. I'll update these tickets once I am able to address this.
